"use client";

import { useState } from "react";

const UNAVAILABLE = "Ask is unavailable right now.";
const MAX_QUESTION_CHARS = 500;
const FOCUS = "focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-station";

/** A plain-English question about the results, answered by Gemini from a summary of FirstDue's numbers. */
export function AskTab() {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  async function send() {
    const text = question.trim();
    if (!text || busy) return;
    setBusy(true);
    setAnswer(null);
    try {
      const response = await fetch("/api/ask", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question: text }),
      });
      const body = (await response.json()) as { answer?: unknown };
      setAnswer(typeof body.answer === "string" && body.answer ? body.answer : UNAVAILABLE);
    } catch {
      setAnswer(UNAVAILABLE);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-col gap-3">
        <h2 className="text-[18px] font-semibold">Ask about the results</h2>
        <p className="text-[14px] leading-[1.55] text-ink-2">
          Ask a question in plain English, such as &quot;How many stations reach 95% of the ceiling?&quot;
        </p>
      </div>
      <form
        className="flex flex-col gap-2"
        onSubmit={(event) => {
          event.preventDefault();
          void send();
        }}
      >
        <label htmlFor="ask-question" className="text-[13px] text-muted">
          Your question
        </label>
        <textarea
          id="ask-question"
          rows={3}
          maxLength={MAX_QUESTION_CHARS}
          value={question}
          disabled={busy}
          onChange={(event) => setQuestion(event.target.value)}
          className={`rounded-md border border-line-strong bg-field px-2.5 py-2 text-[14px] leading-[1.5] text-ink ${FOCUS}`}
        />
        <div>
          <button
            type="submit"
            disabled={busy || !question.trim()}
            className={`min-h-10 cursor-pointer rounded-md border border-station bg-station-bg px-4 text-[13px] text-ink disabled:cursor-not-allowed disabled:border-line-strong disabled:bg-transparent disabled:text-muted ${FOCUS}`}
          >
            {busy ? "Answering…" : "Send"}
          </button>
        </div>
      </form>
      <div role="status" className="text-[14px] leading-[1.55] text-ink-2">
        {answer && <p className="whitespace-pre-wrap rounded-lg bg-card p-3">{answer}</p>}
      </div>
      <p className="text-[12px] leading-[1.5] text-faint">
        Answers generated by Gemini from FirstDue&apos;s results. Check numbers against the other tabs.
      </p>
    </div>
  );
}
